import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { SharedMobilityService } from "./mobility-invitations.js";
import { validateSharedRecordDetails } from "./mobility-service.js";
import { MemoryMobilityStore } from "./mobility-store.js";
import { acceptsMobilitySchema } from "./mobility-contract.js";
import type * as W from "./mobility-types.js";
const actor=(subjectId:string)=>({authMode:"oidc" as const,issuer:"https://synthetic.test",subjectId,username:subjectId,displayName:subjectId,email:subjectId+"@example.test",emailVerified:true});
async function setup(){const store=new MemoryMobilityStore();const service=new SharedMobilityService(store);const a=await service.account(actor("synthetic-a"));const b=await service.account(actor("synthetic-b"));const c=await service.account(actor("synthetic-c"));const v=await service.createVehicle(a,{operationId:randomUUID(),details:{name:"Synthetic"}});const invite=await service.createInvitation(a,"vehicle",v.vehicleId,{operationId:randomUUID(),expectedMembershipRevision:1,email:b.email!,capabilities:["readVehicle","recordExpense","recordService"]});await service.acceptInvitation(b,"vehicle",{operationId:randomUUID(),invitationId:invite.invitationId});return{service,store,a,b,c,id:v.vehicleId}}
const energy=():W.SharedVehicleRecordData=>({kind:"energy",unit:"liters",quantity:"40.5",amount:{currency:"CZK",minorUnits:"162000"},details:{version:1,kind:"refueling",odometerKm:"12345.7",note:"Synthetic note",refueling:{fuelType:"natural95",fullTank:true,quantityBeforeRefueling:"5",station:{name:"Synthetic station",provider:"Synthetic",address:"Synthetic address"}}}});
const receipt=():W.SharedVehicleRecordData=>({kind:"service",title:"Servis",odometerKm:"12345.7",amount:{currency:"CZK",minorUnits:"300000"},details:{version:1,note:"Synthetic service",categoryId:"synthetic-cat",subcategoryId:"synthetic-sub",items:[{itemId:randomUUID(),title:"Synthetic work",categoryId:"synthetic-cat",amount:{currency:"CZK",minorUnits:"100000"}},{itemId:randomUUID(),title:"Synthetic part",amount:{currency:"CZK",minorUnits:"200000"}}]}});
async function request(f:Awaited<ReturnType<typeof setup>>,data:W.SharedVehicleRecordData,recordId=randomUUID(),revision=0){const v=await f.service.getVehicle(f.a,f.id);return{operationId:randomUUID(),recordId,expectedRecordRevision:revision,expectedMembershipRevision:v.membershipRevision,expectedDataRevision:v.dataRevision,occurredAt:"2026-10-05T12:00:00Z",timeZone:"Europe/Prague",data}}
describe("lossless shared receipt details",()=>{
 it("roundtrips every field, one receipt, idempotent retry, preserved service restart and explicit clears",async()=>{const f=await setup();for(const data of[energy(),receipt()]){const q=await request(f,data);const result=await f.service.writeRecord(f.a,f.id,q);expect(await f.service.writeRecord(f.a,f.id,q)).toEqual(result);const sync=await new SharedMobilityService(f.store).syncVehicle(f.a,f.id,undefined);const record=sync.items.find(e=>e.record?.recordId===q.recordId)?.record;expect(record?.data).toEqual(data);expect(sync.items.filter(e=>e.record?.recordId===q.recordId)).toHaveLength(1);await expect(f.service.writeRecord(f.a,f.id,{...q,data:{kind:"energy",unit:"liters",quantity:"1"}})).rejects.toMatchObject({status:409});if(data.kind==="energy"){const clear={...data,details:{version:1 as const,kind:"refueling" as const,note:"",refueling:{fuelType:"natural95" as const}}};await f.service.writeRecord(f.a,f.id,await request(f,clear,q.recordId,1));const next=await f.service.syncVehicle(f.a,f.id,undefined);expect(next.items.filter(e=>e.record?.recordId===q.recordId).at(-1)?.record?.data).toEqual(clear)}}});
 it("blocks details omission, unrelated accounts and cost leakage without partial revision changes",async()=>{const f=await setup();const q=await request(f,energy());await f.service.writeRecord(f.a,f.id,q);const before=await f.service.getVehicle(f.a,f.id);await expect(f.service.writeRecord(f.a,f.id,await request(f,{kind:"energy",unit:"liters",quantity:"40.5"},q.recordId,1))).rejects.toMatchObject({status:409,code:"DETAILS_VERSION_REQUIRED"});expect((await f.service.getVehicle(f.a,f.id)).dataRevision).toBe(before.dataRevision);await expect(f.service.syncVehicle(f.c,f.id,undefined)).rejects.toMatchObject({status:404});const visible=await f.service.syncVehicle(f.b,f.id,undefined);expect(JSON.stringify(visible)).not.toContain("Synthetic note");expect(JSON.stringify(visible)).not.toContain("162000");await expect(f.service.writeRecord(f.b,f.id,await request(f,energy(),q.recordId,1))).rejects.toMatchObject({status:403,code:"AUTHOR_REQUIRED"})});
 it("serializes edits and keeps a complete receipt on a conflict",async()=>{const f=await setup();const q=await request(f,receipt());await f.service.writeRecord(f.a,f.id,q);const change=await request(f,receipt(),q.recordId,1);const results=await Promise.allSettled([1,2].map(()=>f.service.writeRecord(f.a,f.id,{...change,operationId:randomUUID()})));expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1)});
 it("rejects mismatched totals/currencies/duplicate item identities and energy branch/unit errors",()=>{const data=receipt();if(data.kind!=="service")throw Error();expect(()=>validateSharedRecordDetails(data)).not.toThrow();expect(()=>validateSharedRecordDetails({...data,amount:{currency:"CZK",minorUnits:"300001"}})).toThrow();const mixed=structuredClone(data);mixed.details!.items![0]!.amount.currency="EUR";expect(()=>validateSharedRecordDetails(mixed)).toThrow();const duplicate=structuredClone(data);duplicate.details!.items![1]!.itemId=duplicate.details!.items![0]!.itemId;expect(()=>validateSharedRecordDetails(duplicate)).toThrow();const fuel=energy();if(fuel.kind!=="energy")throw Error();expect(()=>validateSharedRecordDetails({...fuel,unit:"kWh"})).toThrow();expect(()=>validateSharedRecordDetails({...fuel,details:{...fuel.details!,refueling:{fuelType:"cng"}}})).toThrow();const charging:W.SharedVehicleRecordData={kind:"energy",unit:"kWh",quantity:"30",details:{version:1,kind:"charging",charging:{source:"home",provider:"Synthetic",locationName:"Synthetic explicit",batteryPercentBefore:"20",batteryPercentAfter:"80",location:{name:"Synthetic",address:"Synthetic"}}}};expect(()=>validateSharedRecordDetails(charging)).not.toThrow();expect(()=>validateSharedRecordDetails({...charging,details:{...charging.details!,charging:{batteryPercentAfter:"100.001"}}})).toThrow();expect(()=>validateSharedRecordDetails({...charging,details:{...charging.details!,charging:{batteryPercentBefore:"80",batteryPercentAfter:"20"}}})).toThrow()});
 it("rejects arbitrary/GPS details and unknown versions; counts Unicode code points without truncation",()=>{const fuel=energy();expect(acceptsMobilitySchema("SharedVehicleRecordData",fuel)).toBe(true);if(fuel.kind!=="energy")throw Error();expect(acceptsMobilitySchema("SharedVehicleRecordData",{...fuel,details:{...fuel.details,lat:50}})).toBe(false);expect(acceptsMobilitySchema("SharedVehicleRecordData",{...fuel,details:{...fuel.details,version:2}})).toBe(false);expect(acceptsMobilitySchema("SharedVehicleRecordData",{...fuel,details:{...fuel.details,note:"🙂".repeat(1000)}})).toBe(true);expect(acceptsMobilitySchema("SharedVehicleRecordData",{...fuel,details:{...fuel.details,note:"🙂".repeat(1001)}})).toBe(false)});
});
