import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { sharedOdometerSnapshot } from "./mobility-odometer.js";
import { SharedMobilityService } from "./mobility-invitations.js";
import { MemoryMobilityStore } from "./mobility-store.js";
import type { VehicleState } from "./mobility-service.js";
import type * as W from "./mobility-types.js";
const now=new Date("2026-10-05T12:00:00Z");
const actor=(subjectId:string)=>({authMode:"oidc" as const,issuer:"https://synthetic.test",subjectId,username:subjectId,displayName:subjectId,email:subjectId+"@example.test",emailVerified:true});
async function setup(){const store=new MemoryMobilityStore();const service=new SharedMobilityService(store,()=>now);const a=await service.account(actor("synthetic-a"));const b=await service.account(actor("synthetic-b"));const v=await service.createVehicle(a,{operationId:randomUUID(),details:{name:"Synthetic km"}});const invite=await service.createInvitation(a,"vehicle",v.vehicleId,{operationId:randomUUID(),expectedMembershipRevision:1,email:b.email!,capabilities:["readVehicle","recordExpense","recordService"]});await service.acceptInvitation(b,"vehicle",{operationId:randomUUID(),invitationId:invite.invitationId});return{store,service,a,b,id:v.vehicleId}}
function record(value:string,date="2026-10-05T11:00:00Z",kind:"energy"|"service"|"odometer"="odometer",correctionOfRecordId?:string):W.SharedVehicleRecord {return{vehicleId:randomUUID(),createdAt:now.toISOString(),recordId:randomUUID(),revision:1,authorAccountId:randomUUID(),occurredAt:date,timeZone:"Europe/Prague",deleted:false,data:kind==="odometer"?{kind,odometerKm:value,...(correctionOfRecordId?{correctionOfRecordId}:{})}:kind==="service"?{kind,title:"Synthetic",odometerKm:value,amount:{currency:"CZK",minorUnits:"12345"}}:{kind,unit:"liters",quantity:"1",details:{version:1,kind:"refueling",odometerKm:value,note:"Synthetic private cost note",refueling:{}},amount:{currency:"CZK",minorUnits:"12345"}}}}
function state(...records:W.SharedVehicleRecord[]):VehicleState{const id=randomUUID();for(const record of records)record.vehicleId=id;return{vehicle:{contractVersion:"cop-shared-vehicles-v1",vehicleId:id,details:{name:"Synthetic"},dataRevision:8,membershipRevision:1,members:[],createdAt:now.toISOString(),updatedAt:now.toISOString(),deleted:false},records:Object.fromEntries(records.map(r=>[r.recordId,r])),events:[],sequence:0}}
describe("authoritative shared odometer whole-state projection",()=>{
 it("knows all receipt kinds, orders by observation time, never sums or exposes costs",()=>{const old=record("100","2026-10-01T11:00:00Z","service"),latest=record("120.5",undefined,"energy");const s=state(latest,old);expect(sharedOdometerSnapshot(s,now)).toMatchObject({version:1,status:"known",dataRevision:8,valueKm:"120.5",source:{recordId:latest.recordId,recordKind:"energy"}});const text=JSON.stringify(sharedOdometerSnapshot(s,now));expect(text).not.toContain("12345");expect(text).not.toContain("private cost note");expect(text).not.toContain("authorAccountId")});
 it("uses unknown, deterministic same-date equality and review for contradictions/decreases/future/invalid values",()=>{expect(sharedOdometerSnapshot(state(),now)).toMatchObject({status:"unknown",reason:"no_observations"});for(const[records,reason]of[[[record("100"),record("101")],"conflicting_observations"],[[record("101","2026-10-04T11:00:00Z"),record("100")],"decreasing_observation"],[[record("100","2026-10-06T11:00:00Z")],"future_observation"],[[record("bad")],"invalid_observation"]] as const){const value=sharedOdometerSnapshot(state(...records),now);expect(value).toMatchObject({status:"reviewRequired",reason});expect(value.valueKm).toBeUndefined()}const x=record("100"),y=record("100.000");expect(sharedOdometerSnapshot(state(x,y),now)).toEqual(sharedOdometerSnapshot(state(y,x),now))});
 it("applies correction chains, removes exclusions after tombstone, rejects cycles/invalid references",()=>{const original=record("500","2026-10-01T11:00:00Z"),correction=record("100","2026-10-01T11:00:00Z","odometer",original.recordId),latest=record("120");const s=state(original,correction,latest);expect(sharedOdometerSnapshot(s,now).valueKm).toBe("120");correction.deleted=true;expect(sharedOdometerSnapshot(s,now).reason).toBe("decreasing_observation");correction.deleted=false;const next=record("99","2026-10-01T11:00:00Z","odometer",correction.recordId);next.vehicleId=s.vehicle.vehicleId;s.records[next.recordId]=next;expect(sharedOdometerSnapshot(s,now).valueKm).toBe("120");next.data={kind:"odometer",odometerKm:"99",correctionOfRecordId:next.recordId};expect(sharedOdometerSnapshot(s,now).reason).toBe("invalid_correction");const broken=record("1",undefined,"odometer",randomUUID());expect(sharedOdometerSnapshot(state(broken),now).reason).toBe("invalid_correction");const a=record("1"),b=record("2");a.data={kind:"odometer",odometerKm:"1",correctionOfRecordId:b.recordId};b.data={kind:"odometer",odometerKm:"2",correctionOfRecordId:a.recordId};expect(sharedOdometerSnapshot(state(a,b),now).reason).toBe("invalid_correction")});
 it("recomputes revisions/tombstones and never invents an observation from a ride or quantity",()=>{const old=record("10","2026-10-01T11:00:00Z"),latest=record("20");const s=state(old,latest);latest.deleted=true;s.vehicle.dataRevision=9;expect(sharedOdometerSnapshot(s,now)).toMatchObject({valueKm:"10",dataRevision:9,observedAt:old.occurredAt});old.deleted=true;expect(sharedOdometerSnapshot(s,now).status).toBe("unknown");latest.deleted=false;latest.data={kind:"energy",unit:"liters",quantity:"50"};expect(sharedOdometerSnapshot(s,now).status).toBe("unknown")});
 it("returns equal owner/driver snapshots without readCosts, including incomplete sync page and receipt",async()=>{const f=await setup();for(const[value,date,kind]of[["100","2026-10-04T11:00:00Z","service"],["120","2026-10-05T11:00:00Z","energy"]]as const){const r=record(value,date,kind);const v=await f.service.getVehicle(f.b,f.id);const result=await f.service.writeRecord(f.b,f.id,{operationId:randomUUID(),recordId:r.recordId,expectedRecordRevision:0,expectedDataRevision:v.dataRevision,expectedMembershipRevision:v.membershipRevision,occurredAt:r.occurredAt,timeZone:r.timeZone,data:r.data});expect(result.odometerSnapshot).toMatchObject({valueKm:value,dataRevision:result.dataRevision})}const a=await f.service.getVehicle(f.a,f.id),b=await f.service.getVehicle(f.b,f.id);expect(a.odometerSnapshot).toEqual(b.odometerSnapshot);expect(b.odometerSnapshot?.valueKm).toBe("120");expect((await f.service.listVehicles(f.b)).items[0]?.odometerSnapshot).toEqual(b.odometerSnapshot);const page=await f.service.syncVehicle(f.b,f.id,undefined,1);expect(page.hasMore).toBe(true);expect(page.odometerSnapshot).toEqual(b.odometerSnapshot);const all=await f.service.syncVehicle(f.b,f.id,undefined);expect(JSON.stringify(all)).not.toContain("12345");expect(JSON.stringify(all)).not.toContain("private cost note")});
});
