import {randomUUID} from "node:crypto";
import {describe,expect,it} from "vitest";
import {PostgresMobilityStore} from "./mobility-store.js";
import {SharedMobilityService} from "./mobility-invitations.js";
import type * as W from "./mobility-types.js";
const connectionString=process.env.COP_RECORD_DETAILS_TEST_DATABASE_URL;
if(connectionString){const url=new URL(connectionString);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.pathname!=="/cop_record_details_test")throw Error("Requires isolated loopback cop_record_details_test database")}
describe.skipIf(!connectionString)("real PostgreSQL completed rides v2",()=>{
 it("atomically appends both historical-revision trips once across connections/restart and covers them with a later reading",async()=>{const first=new PostgresMobilityStore({connectionString,max:3}),second=new PostgresMobilityStore({connectionString,max:3});try{await first.init();await second.init();const s=new SharedMobilityService(first,()=>new Date("2026-10-05T12:00:00Z")),t=new SharedMobilityService(second,()=>new Date("2026-10-05T12:00:00Z"));const actor={authMode:"oidc" as const,issuer:"https://synthetic.test",subjectId:"synthetic-"+randomUUID(),displayName:"Synthetic",username:"Synthetic"};const account=await s.account(actor);const vehicle=await s.createVehicle(account,{operationId:randomUUID(),details:{name:"Synthetic"}});const base={operationId:randomUUID(),recordId:randomUUID(),expectedRecordRevision:0,expectedDataRevision:1,expectedMembershipRevision:1,occurredAt:"2026-10-05T01:00:00Z",timeZone:"UTC",data:{kind:"odometer" as const,odometerKm:"100",initial:true as const}};await s.writeRecord(account,vehicle.vehicleId,base);const q=(distance:string,start:number,end:number):W.SharedVehicleRecordWrite=>({operationId:randomUUID(),recordId:randomUUID(),expectedRecordRevision:0,expectedDataRevision:2,expectedMembershipRevision:1,occurredAt:`2026-10-05T0${end}:00:00Z`,timeZone:"UTC",data:{kind:"ride_summary",distanceKm:distance,durationSeconds:60,purpose:"work",details:{version:1,tripId:randomUUID(),startedAt:`2026-10-05T0${start}:00:00Z`,endedAt:`2026-10-05T0${end}:00:00Z`}}});const a=q("10.125",2,3),b=q("20.25",3,4);const receipts=await Promise.all([s.writeRecord(account,vehicle.vehicleId,a),t.writeRecord(account,vehicle.vehicleId,b)]);expect((await t.getVehicle(account,vehicle.vehicleId)).odometerSnapshotV2).toMatchObject({status:"estimated",valueKm:"130.375",includedRideCount:2});expect(await t.writeRecord(account,vehicle.vehicleId,a)).toEqual(receipts[0]);await expect(t.writeRecord(account,vehicle.vehicleId,{...a,operationId:randomUUID(),recordId:randomUUID()})).rejects.toMatchObject({code:"DUPLICATE_RIDE_ID"});const v=await t.getVehicle(account,vehicle.vehicleId);await t.writeRecord(account,vehicle.vehicleId,{...base,operationId:randomUUID(),recordId:randomUUID(),expectedDataRevision:v.dataRevision,occurredAt:"2026-10-05T05:00:00Z",data:{kind:"odometer",odometerKm:"129"}});expect((await s.getVehicle(account,vehicle.vehicleId)).odometerSnapshotV2).toMatchObject({status:"known",valueKm:"129"});}finally{await first.close();await second.close()}});
});
