import {randomUUID} from "node:crypto";
import {describe,expect,it} from "vitest";
import {sharedOdometerSnapshotV2,sharedMileageViews} from "./mobility-mileage.js";
import {SharedMobilityService} from "./mobility-invitations.js";
import {MemoryMobilityStore} from "./mobility-store.js";
import type {VehicleState} from "./mobility-service.js";
import type * as W from "./mobility-types.js";
const now=new Date("2026-10-05T12:00:00Z");
const at=(hour:number)=>`2026-10-05T${hour.toString().padStart(2,"0")}:00:00Z`;
const reading=(value="100",hour=1):W.SharedVehicleRecord=>({recordId:randomUUID(),vehicleId:randomUUID(),authorAccountId:randomUUID(),createdAt:at(0),occurredAt:at(hour),timeZone:"UTC",revision:1,deleted:false,data:{kind:"odometer",odometerKm:value}});
const ride=(value="10",start=2,end=3,endOdometerKm?:string):W.SharedVehicleRecord=>({...reading(),occurredAt:at(end),data:{kind:"ride_summary",distanceKm:value,durationSeconds:60,purpose:"work",details:{version:1,tripId:randomUUID(),startedAt:at(start),endedAt:at(end),...(endOdometerKm?{endOdometerKm}:{})}}});
const state=(...records:W.SharedVehicleRecord[]):VehicleState=>{const vehicleId=randomUUID();records.forEach(r=>r.vehicleId=vehicleId);return{vehicle:{contractVersion:"cop-shared-vehicles-v1",vehicleId,details:{name:"Synthetic"},dataRevision:8,membershipRevision:1,members:[],createdAt:at(0),updatedAt:at(0),deleted:false},records:Object.fromEntries(records.map(r=>[r.recordId,r])),events:[],sequence:0}};
const actor=(subjectId:string)=>({authMode:"oidc" as const,issuer:"https://synthetic.test",subjectId,username:subjectId,displayName:subjectId,email:subjectId+"@example.test",emailVerified:true});
async function setup(){const store=new MemoryMobilityStore();const service=new SharedMobilityService(store,()=>now);const a=await service.account(actor("synthetic-owner")),b=await service.account(actor("synthetic-b")),c=await service.account(actor("synthetic-c"));const v=await service.createVehicle(a,{operationId:randomUUID(),details:{name:"Synthetic"}});for(const account of[b,c]){const invite=await service.createInvitation(a,"vehicle",v.vehicleId,{operationId:randomUUID(),expectedMembershipRevision:(await service.getVehicle(a,v.vehicleId)).membershipRevision,email:account.email!,capabilities:["readVehicle","recordRide","recordExpense","editVehicle"]});await service.acceptInvitation(account,"vehicle",{operationId:randomUUID(),invitationId:invite.invitationId})}return{store,service,a,b,c,id:v.vehicleId}}
async function input(f:Awaited<ReturnType<typeof setup>>,account:W.MobilityAccount,r:W.SharedVehicleRecord,revision=0){const v=await f.service.getVehicle(account,f.id);return{operationId:randomUUID(),recordId:r.recordId,expectedRecordRevision:revision,expectedDataRevision:v.dataRevision,expectedMembershipRevision:v.membershipRevision,occurredAt:r.occurredAt,timeZone:r.timeZone,data:r.data}}
describe("completed shared mileage v2",()=>{
 it("adds exact deduplicated completed distances regardless of submission order, never calls calculation known",()=>{const a=reading(),b=ride("10.125",2,3),c=ride("20.25",3,4);const result=sharedOdometerSnapshotV2(state(c,a,b),now);expect(result).toMatchObject({version:2,status:"estimated",valueKm:"130.375",basisKm:"100",includedRideCount:2,unconfirmedDistanceKm:"30.375"});expect(sharedMileageViews(state(a,b,c),now).odometerSnapshot).toEqual({version:1,status:"reviewRequired",dataRevision:8})});
 it("a later instrument reading covers preceding rides once, with no double addition",()=>{const a=reading(),b=ride("10",2,3),c=ride("20",3,4),d=reading("129",5),e=ride("5",6,7);expect(sharedOdometerSnapshotV2(state(e,c,d,a,b),now)).toMatchObject({status:"estimated",valueKm:"134",basisKm:"129",includedRideCount:1});expect(sharedOdometerSnapshotV2(state(a,b,c,d),now)).toMatchObject({status:"known",valueKm:"129"})});
 it("reviews overlap, reading inside trip, unknown legacy intervals, duplicate trip and overflow",()=>{const a=ride(),b=ride("20",2,4);const r=b.data;if(r.kind!=="ride_summary")throw Error();const cases:Array<[W.SharedVehicleRecord[],string]>=[[[reading(),a,b],"overlapping_rides"],[[reading("100",3),ride("5",2,4)],"anchor_overlap"],[[reading("999999999.999"),ride("0.001")],"distance_overflow"]];const duplicate=ride();if(duplicate.data.kind!=="ride_summary"||a.data.kind!=="ride_summary")throw Error();duplicate.data.details!.tripId=a.data.details!.tripId;cases.push([[reading(),a,duplicate],"duplicate_trip"]);const legacy=ride();if(legacy.data.kind!=="ride_summary")throw Error();delete legacy.data.details;cases.push([[reading(),legacy],"legacy_ride_interval_unknown"]);for(const[records,reason]of cases){const value=sharedOdometerSnapshotV2(state(...records),now);expect(value).toMatchObject({status:"reviewRequired",reason});expect(value.valueKm).toBeUndefined()}});
 it("uses actual ride end reading as known and recalculates after tombstone, never invents a baseline",()=>{const a=reading(),b=ride("10",2,3,"112"),c=ride("5",4,5);const s=state(a,b,c);expect(sharedOdometerSnapshotV2(s,now)).toMatchObject({status:"estimated",valueKm:"117",basisKm:"112",basisSource:{recordKind:"ride_summary"}});c.deleted=true;expect(sharedOdometerSnapshotV2(s,now)).toMatchObject({status:"known",valueKm:"112",source:{recordKind:"ride_summary"}});b.deleted=true;expect(sharedOdometerSnapshotV2(s,now)).toMatchObject({status:"known",valueKm:"100"});expect(sharedOdometerSnapshotV2(state(ride()),now).status).toBe("unknown")});
 it("seeds once with owner/CAS/idempotence then shares both drivers' full summaries and equal snapshots without costs",async()=>{const f=await setup();const seed=reading();seed.data={kind:"odometer",odometerKm:"100",initial:true};await expect(f.service.writeRecord(f.b,f.id,await input(f,f.b,seed))).rejects.toMatchObject({status:403,code:"OWNER_REQUIRED"});const q=await input(f,f.a,seed);const second={...q,operationId:randomUUID()};const results=await Promise.allSettled([q,second].map(value=>f.service.writeRecord(f.a,f.id,value)));expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1);const winner=results.find((x):x is PromiseFulfilledResult<W.SharedVehicleReceipt>=>x.status==="fulfilled")!.value;expect(await f.service.writeRecord(f.a,f.id,{...q,operationId:winner.operationId})).toEqual(winner);await expect(f.service.writeRecord(f.a,f.id,await input(f,f.a,{...seed,recordId:randomUUID()}))).rejects.toMatchObject({status:409,code:"INITIAL_ODOMETER_EXISTS"});for(const[account,r]of[[f.b,ride("10.125",2,3)],[f.c,ride("20.25",3,4)]]as const){const request=await input(f,account,r);const receipt=await f.service.writeRecord(account,f.id,request);expect(await f.service.writeRecord(account,f.id,request)).toEqual(receipt)}const owner=await f.service.getVehicle(f.a,f.id);for(const account of[f.b,f.c])expect((await f.service.getVehicle(account,f.id)).odometerSnapshotV2).toEqual(owner.odometerSnapshotV2);expect(owner.odometerSnapshotV2?.valueKm).toBe("130.375");const full=await f.service.syncVehicle(f.a,f.id,undefined);expect(new Set(full.items.filter(x=>x.record?.data.kind==="ride_summary").map(x=>x.record!.authorAccountId))).toEqual(new Set([f.b.accountId,f.c.accountId]));const page=await f.service.syncVehicle(f.b,f.id,undefined,1);expect(page.hasMore).toBe(true);expect(page.odometerSnapshotV2).toEqual(owner.odometerSnapshotV2)});
 it("reserves immutable trip IDs including tombstones, rejects detail omission without mutation and supports author-correct owner edits",async()=>{const f=await setup();const a=reading();await f.service.writeRecord(f.a,f.id,await input(f,f.a,a));const b=ride();await f.service.writeRecord(f.b,f.id,await input(f,f.b,b));const before=await f.service.getVehicle(f.a,f.id);await expect(f.service.writeRecord(f.b,f.id,await input(f,f.b,{...b,recordId:randomUUID()}))).rejects.toMatchObject({status:409,code:"DUPLICATE_RIDE_ID"});if(b.data.kind!=="ride_summary")throw Error();const legacy={...b,data:{kind:"ride_summary" as const,distanceKm:"10",durationSeconds:60,purpose:"work" as const}};await expect(f.service.writeRecord(f.b,f.id,await input(f,f.b,legacy,1))).rejects.toMatchObject({status:409,code:"DETAILS_VERSION_REQUIRED"});const changed=structuredClone(b);if(changed.data.kind!=="ride_summary")throw Error();changed.data.details!.tripId=randomUUID();await expect(f.service.writeRecord(f.b,f.id,await input(f,f.b,changed,1))).rejects.toMatchObject({status:409,code:"RIDE_ID_IMMUTABLE"});expect((await f.service.getVehicle(f.a,f.id)).dataRevision).toBe(before.dataRevision);await f.service.writeRecord(f.a,f.id,await input(f,f.a,{...b,data:{...b.data,distanceKm:"11"}},1));const sync=await f.service.syncVehicle(f.a,f.id,undefined);expect(sync.items.filter(x=>x.record?.recordId===b.recordId).at(-1)?.record?.authorAccountId).toBe(f.b.accountId);const v=await f.service.getVehicle(f.a,f.id);await f.service.deleteRecord(f.a,f.id,{operationId:randomUUID(),recordId:b.recordId,expectedRecordRevision:2,expectedDataRevision:v.dataRevision,expectedMembershipRevision:v.membershipRevision,reason:"Synthetic delete"});await expect(f.service.writeRecord(f.b,f.id,await input(f,f.b,{...b,recordId:randomUUID()}))).rejects.toMatchObject({code:"DUPLICATE_RIDE_ID"})});
 it("accepts only independent detailed ride appends with historical data revision while keeping membership and edits strict",async()=>{const f=await setup();await f.service.writeRecord(f.a,f.id,await input(f,f.a,reading()));const a=ride("10",2,3),b=ride("20",3,4);const first=await input(f,f.b,a),second=await input(f,f.c,b);expect(first.expectedDataRevision).toBe(second.expectedDataRevision);const result=await Promise.all([f.service.writeRecord(f.b,f.id,first),f.service.writeRecord(f.c,f.id,second)]);expect(result).toHaveLength(2);expect((await f.service.getVehicle(f.a,f.id)).odometerSnapshotV2).toMatchObject({status:"estimated",valueKm:"130",includedRideCount:2});expect(await f.service.writeRecord(f.b,f.id,first)).toEqual(result[0]);const fresh=ride("1",5,6);await expect(f.service.writeRecord(f.b,f.id,{...await input(f,f.b,fresh),expectedDataRevision:1,expectedMembershipRevision:1})).rejects.toMatchObject({status:409,code:"REVISION_CONFLICT"});await expect(f.service.writeRecord(f.b,f.id,{...await input(f,f.b,fresh),expectedDataRevision:999})).rejects.toMatchObject({status:409});const legacy={...fresh,data:{kind:"ride_summary" as const,distanceKm:"1",durationSeconds:60,purpose:"work" as const}};await expect(f.service.writeRecord(f.b,f.id,{...await input(f,f.b,legacy),expectedDataRevision:1})).rejects.toMatchObject({status:409});await expect(f.service.writeRecord(f.b,f.id,{...first,operationId:randomUUID(),expectedRecordRevision:1})).rejects.toMatchObject({status:409})});

});
